### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .css_freznel_2026 import css_freznel_2026

def create_instance(c_instance):
	return css_freznel_2026(c_instance)